{
 "title": "Pizza Dashbard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "latency__{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "latency__menu{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"counter\", __proxy_source__=\"influx\", source=\"jwt-pizza-service-dev\", type=\"orders.revenue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"counter\", __proxy_source__=\"influx\", source=\"jwt-pizza-service-dev\", type=\"orders.success\"}\r\n",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Authentifications",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_count{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "request_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "user_count{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}